package vida

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/alkemist-17/vida/token"
)

// bundlePrefix names the synthetic globals the bundler introduces to stand
// in for each flattened dependency. It is deliberately unusual so it will
// not collide with identifiers a person would plausibly write by hand.
const bundlePrefix = "__vida_bundle_"

// Bundle is the result of flattening a script's import graph into a single
// self-contained source file.
type Bundle struct {
	// Source is the generated, single-file .vida program. It has no
	// remaining local import(...) calls: every local dependency has been
	// inlined. Remote imports (disallowed directly in code, same as in
	// ordinary compilation) still surface as an error during bundling.
	Source []byte
	// Entry is the resolved, absolute path of the script that was bundled.
	Entry string
	// Files lists every file folded into Source, starting with Entry,
	// followed by its dependencies in the order they were first
	// encountered (depth-first).
	Files []string
}

// BundleSource walks entryPath's import graph -- exactly the same
// resolution rules the compiler itself uses (relative to each importing
// file, then that file's 'cells' directory, then VIDAPATH) -- and produces
// a single .vida file with every local dependency inlined.
//
// Each dependency is wrapped as `let __vida_bundle_N = fun { ... }` and
// every import("...") call site that used to load it becomes a call to
// that function, preserving the original re-execute-on-every-import
// semantics. A dependency's own top-level `let` declarations are rewritten
// to `var` so that dependencies don't collide in a shared global namespace
// once they're all compiled as one program (they're independent modules
// in the original multi-file compilation; wrapping keeps them
// independent). A dependency's trailing `export <expr>` becomes
// `ret <expr>`, matching how import() already treats it. The entry
// file itself is left otherwise untouched -- its own top-level `let`s and
// any `export` (a no-op at the true top level, exactly as it is today)
// keep their original meaning.
func BundleSource(entryPath string) (*Bundle, error) {
	abs, err := filepath.Abs(entryPath)
	if err != nil {
		return nil, fmt.Errorf("bundler: %w", err)
	}
	if !strings.HasSuffix(abs, VidaFileExtension) {
		return nil, fmt.Errorf("bundler: %q is not a %v file", entryPath, VidaFileExtension)
	}
	if !fileExistsOnDisk(abs) {
		return nil, fmt.Errorf("bundler: entry file '%v' cannot be found in your system", entryPath)
	}

	b := &bundler{
		bundleIDs:  make(map[string]int),
		inProgress: make(map[string]bool),
		nextID:     1,
	}

	entryBody, err := b.process(abs, true)
	if err != nil {
		return nil, err
	}

	var out strings.Builder
	out.WriteString("// Generated by `vida bundle`. Do not edit by hand.\n")
	fmt.Fprintf(&out, "// entry: %v\n\n", abs)
	for _, decl := range b.prelude {
		out.WriteString(decl)
		out.WriteString("\n")
	}
	out.WriteString(entryBody)
	out.WriteString("\n")

	return &Bundle{
		Source: []byte(out.String()),
		Entry:  abs,
		Files:  append([]string{abs}, b.files...),
	}, nil
}

type bundler struct {
	bundleIDs  map[string]int  // resolved absolute path -> its __vida_bundle_N id
	inProgress map[string]bool // resolved absolute path -> currently being processed (cycle guard)
	prelude    []string        // generated `let __vida_bundle_N = fun {...}` declarations, dependency-first
	files      []string        // dependencies in first-encountered order, for diagnostics
	nextID     int
}

// process reads, validates, and rewrites a single file, recursively
// bundling any dependency it imports before it returns -- so callers that
// append process's own result to b.prelude naturally end up with
// dependency-first ordering, which is required: Vida resolves a global
// identifier at the point it's referenced during compilation, so a
// __vida_bundle_N call inside another bundle function must be declared
// before it's used.
func (b *bundler) process(path string, isEntry bool) (string, error) {
	if b.inProgress[path] {
		return EmptyString, fmt.Errorf("bundler: import cycle detected involving '%v'", path)
	}
	b.inProgress[path] = true
	defer delete(b.inProgress, path)

	raw, err := os.ReadFile(path)
	if err != nil {
		return EmptyString, fmt.Errorf("bundler: could not read %v: %w", path, err)
	}

	// Validate with the real parser first. Everything after this point
	// assumes the token stream is grammatically valid Vida, which is what
	// lets the lightweight token scan below treat 'import', 'let', and
	// 'export' as unambiguous, context-free markers instead of having to
	// reimplement the grammar.
	if _, perr := newParser(raw, path).parse(); perr != nil {
		return EmptyString, perr
	}

	toks, lerr := scanTokenPositions(raw, path)
	if lerr != nil {
		return EmptyString, lerr
	}

	imports, edits := scanRewriteTargets(toks, !isEntry)

	baseDir := filepath.Dir(path)
	for _, imp := range imports {
		rawPath, derr := decodeImportLiteral(imp.lit)
		if derr != nil {
			return EmptyString, NewRuntimeError(path, derr.Error(), BuildErrType, imp.line)
		}
		depPath, rerr := resolveImportPathFromDir(baseDir, rawPath)
		if rerr != nil {
			return EmptyString, NewRuntimeError(path, rerr.Error(), BuildErrType, imp.line)
		}

		id, seen := b.bundleIDs[depPath]
		if !seen {
			depBody, derr := b.process(depPath, false)
			if derr != nil {
				return EmptyString, derr
			}
			id = b.nextID
			b.nextID++
			b.bundleIDs[depPath] = id
			b.prelude = append(b.prelude, fmt.Sprintf("let %v%d = fun {\n%v\n}\n", bundlePrefix, id, depBody))
			b.files = append(b.files, depPath)
		}

		edits = append(edits, sourceEdit{
			start:       imp.start,
			end:         imp.end,
			replacement: fmt.Sprintf("%v%d()", bundlePrefix, id),
		})
	}

	rewritten, aerr := applyEdits(raw, edits)
	if aerr != nil {
		return EmptyString, aerr
	}
	return rewritten, nil
}

// importCall is one `import("...")` call site found in a file, with the
// exact source span it occupies (so it can be replaced) and its literal
// argument text (still lexer-quoted, exactly as parser.go itself expects
// before strconv.Unquote is applied).
type importCall struct {
	start, end int
	line       uint
	lit        string
}

// sourceEdit replaces src[start:end] with replacement.
type sourceEdit struct {
	start, end  int
	replacement string
}

// scanRewriteTargets walks a file's token stream (already known to be
// grammatically valid) looking for three constructs, each of which is a
// reserved keyword usable in exactly one unambiguous shape by the grammar,
// so a flat token scan -- no recursive-descent parsing needed -- can find
// every occurrence safely:
//
//   - import("...") call expressions, wherever they appear (import is a
//     primary expression in Vida, not a statement, so these can be
//     anywhere an expression is valid).
//   - top-level `let` / `let a, b = ...` declarations, when
//     convertModuleLevelDecls is set. `let` never appears inside a nested
//     block in valid Vida (only the file's own top-level parse loop
//     accepts it), so every occurrence found this way is one of these
//     declarations.
//   - a trailing `export <expr>`, when convertModuleLevelDecls is set.
//     Symmetrically, `export` is only ever accepted as the very last
//     top-level statement of a file.
func scanRewriteTargets(toks []posToken, convertModuleLevelDecls bool) (imports []importCall, edits []sourceEdit) {
	for i := 0; i < len(toks); i++ {
		t := toks[i]
		switch t.tok {
		case token.IMPORT:
			if i+3 < len(toks) &&
				toks[i+1].tok == token.LPAREN &&
				toks[i+2].tok == token.STRING &&
				toks[i+3].tok == token.RPAREN {
				imports = append(imports, importCall{
					start: t.start,
					end:   toks[i+3].end,
					line:  t.line,
					lit:   toks[i+2].lit,
				})
				i += 3
			}
		case token.LET:
			if convertModuleLevelDecls {
				edits = append(edits, sourceEdit{start: t.start, end: t.end, replacement: "var"})
			}
		case token.EXPORT:
			if convertModuleLevelDecls {
				edits = append(edits, sourceEdit{start: t.start, end: t.end, replacement: "ret"})
			}
		}
	}
	return imports, edits
}

// decodeImportLiteral mirrors the exact transform parser.go applies to an
// import(...) argument: unquote the string literal (accepting both
// "double-quoted" and `backtick-raw` forms, same as strconv.Unquote), then
// append the .vida extension unless the path is a remote (http/https) URL.
func decodeImportLiteral(lit string) (string, error) {
	s, err := strconv.Unquote(lit)
	if err != nil {
		return EmptyString, fmt.Errorf("invalid import path literal %v: %w", lit, err)
	}
	if isRemoteImport(s) {
		return s, nil
	}
	return s + VidaFileExtension, nil
}

// posToken is one lexer token together with its exact byte span in the
// original source, which the plain Lexer.Next() API doesn't expose.
type posToken struct {
	tok        token.Token
	lit        string
	line       uint
	start, end int
}

// scanTokenPositions re-lexes src, recording each token's byte span. A
// token's start is the previous token's end, so any whitespace or
// comments between them is folded into whichever span is later replaced
// or removed -- harmless, since every replacement in this file works on
// whole syntactic units (a whole import(...) call, or a single keyword)
// and never needs to preserve exact original spacing around it.
func scanTokenPositions(src []byte, scriptID string) ([]posToken, *VidaRunTimeError) {
	l := newLexer(src, scriptID)
	toks := make([]posToken, 0, len(src)/4+8)
	prevEnd := 0
	for {
		line, tok, lit := l.Next()
		if l.LexicalError != nil {
			return toks, l.LexicalError
		}
		end := l.pointer
		if tok == token.COMMENT {
			prevEnd = end
			continue
		}
		toks = append(toks, posToken{tok: tok, lit: lit, line: line, start: prevEnd, end: end})
		prevEnd = end
		if tok == token.EOF {
			break
		}
	}
	return toks, nil
}

// applyEdits rewrites src by replacing every edit's [start:end) span with
// its replacement text, left to right.
func applyEdits(src []byte, edits []sourceEdit) (string, error) {
	sort.Slice(edits, func(i, j int) bool { return edits[i].start < edits[j].start })

	var b strings.Builder
	cursor := 0
	for _, e := range edits {
		if e.start < cursor {
			return EmptyString, fmt.Errorf("bundler: internal error, overlapping source edits")
		}
		if e.start > len(src) || e.end > len(src) || e.end < e.start {
			return EmptyString, fmt.Errorf("bundler: internal error, edit out of bounds")
		}
		b.Write(src[cursor:e.start])
		b.WriteString(e.replacement)
		cursor = e.end
	}
	b.Write(src[cursor:])
	return b.String(), nil
}
