package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/alkemist-17/vida"
)

const (
	lockFileName = "vida.lock"
)

func writeLockFile(path string, locked map[string]string) error {
	names := make([]string, 0, len(locked))
	for name := range locked {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# generated by 'vida install' — do not edit by hand\n\n")
	for _, name := range names {
		fmt.Fprintf(&b, "%v = %q\n", name, locked[name])
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func install(args []string) {
	clear()
	printVersion()

	cwd, err := os.Getwd()
	handleError(err)

	manifestPath := filepath.Join(cwd, manifestFileName)
	if !fileExistsOnDiskCLI(manifestPath) {
		handleError(fmt.Errorf("no %v found in the current directory", manifestFileName))
	}

	m, err := readManifest(manifestPath)
	handleError(err)

	if len(args) > 2 {
		installOne(cwd, manifestPath, &m, args)
		return
	}

	installAll(cwd, m)
}

// installOne handles 'vida install <name> <url>': downloads a single
// module ad-hoc, records it in vida.toml so it's reproducible for anyone
// else who runs 'vida install' with no args, and updates vida.lock.
func installOne(cwd, manifestPath string, m *manifest, args []string) {
	if len(args) < 4 {
		handleError(fmt.Errorf("usage: vida install <name> <url>"))
	}
	name := args[2]
	depURL := args[3]

	cellsDir := filepath.Join(cwd, vida.ProjectCellsDir)
	handleError(os.MkdirAll(cellsDir, 0o755))

	destPath := filepath.Join(cellsDir, name+vida.VidaFileExtension)
	fmt.Printf("\t⬇  %-20v %v\n", name, depURL)

	if err := vida.DownloadCellTo(depURL, destPath); err != nil {
		handleError(err)
	}

	if m.Dependencies == nil {
		m.Dependencies = make(map[string]string)
	}
	m.Dependencies[name] = depURL
	handleError(writeManifest(manifestPath, *m))
	handleError(writeLockFile(filepath.Join(cwd, lockFileName), m.Dependencies))

	fmt.Printf("\n\n\t✅ installed %v and updated %v\n\n\n\n", name, manifestFileName)
}

// installAll handles bare 'vida install': downloads every dependency
// listed in vida.toml. This is the previous behavior, unchanged.
func installAll(cwd string, m manifest) {
	if len(m.Dependencies) == 0 {
		fmt.Printf("\tNo dependencies listed in %v.\n\n\n\n", manifestFileName)
		return
	}

	cellsDir := filepath.Join(cwd, vida.ProjectCellsDir)
	handleError(os.MkdirAll(cellsDir, 0o755))

	names := make([]string, 0, len(m.Dependencies))
	for name := range m.Dependencies {
		names = append(names, name)
	}
	sort.Strings(names)

	locked := make(map[string]string, len(names))
	failed := 0

	for _, name := range names {
		depURL := m.Dependencies[name]
		destPath := filepath.Join(cellsDir, name+vida.VidaFileExtension)
		fmt.Printf("\t⬇  %-20v %v\n", name, depURL)

		if err := vida.DownloadCellTo(depURL, destPath); err != nil {
			fmt.Printf("\t❌ %v\n", err)
			failed++
			continue
		}
		locked[name] = depURL
	}

	handleError(writeLockFile(filepath.Join(cwd, lockFileName), locked))

	fmt.Printf("\n\n\t%v installed, %v failed\n\n\n\n", len(locked), failed)
	if failed > 0 {
		os.Exit(1)
	}
}
